### ISSUE TITLE
Inquiry regarding the prepare of raw sequence data in metatranscriptomics

### ISSUE THREAD

**Issue by Lafmas** [ablab/metaGT#2]
Hello!

Recently, while I was researching metatranscriptomics, I came across the metaGT tool that you developed. I am writing to inquire if there is a specific manual for metaGT available. I have read the paper published in Frontiers, however, I did not comprehend it well as I am a beginner in the NGS field.

My question is, how should I prepare raw sequence files for metatranscriptomics? For metagenomics, our plan is to prepare raw fastq files using shotgun sequencing.

Thank you for your time and I look forward to hearing from you soon.

Best regards,
Lafmas

**Comment by andrewprzh** [comment]
Dear @Lafmas 

For metatranscriptomic data MetaGT similarly expects raw FASTQ files from Illumina sequencer. It also expects reads to be adapter-trimmed, but it is usually done automatically by the sequencer.

To get information about the pipeline you can clone GitHub repository and run 
```
nextflow run metaGT --help
```

I will add all the information to the README soon. Thank you for pointing that out!

Best
Andrey

**Comment by Lafmas** [comment]
Thank!

Then, could you please recommend whether single-end or paired-end sequencing is better for metatranscriptomic data in metaGT? The read length will be 150 bp.

Best regards,
Lafmas

**Comment by Lafmas** [comment]
I have one more question. 

Is it possible to install metaGT using Bioconda rather than cloning the repository from Git? 

Best regards,
Lafmas

**Comment by andrewprzh** [comment]
>Then, could you please recommend whether single-end or paired-end sequencing is better for metatranscriptomic data in metaGT? The read length will be 150 bp.

MetaGT uses rnaSPAdes inside to perfrom draft transcriptome assembly. Based on my experience paired-end reads typically give noticeably better results (especially for eukaryotic samples). However, if you work with batcterial community the difference may less significant. I'd vote for paired-end reads, but it also depends on the cost etc.

>Is it possible to install metaGT using Bioconda rather than cloning the repository from Git?

Not yet, but we'll figure it out at some point.

Best
Andrey

**Comment by Lafmas** [comment]
Thank you for your kind reply!

I`ll prepare pair-end reads and install using git clone.

Best
Lafmas
