### ISSUE TITLE
Failure in running test. 

### ISSUE THREAD

**Issue by JSSaini** [ablab/metaGT#4]
`nextflow run metaGT -profile test,conda
`
```
N E X T F L O W  ~  version 22.10.4
Pulling nextflow-io/metaGT ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nextflow-io/metaGT/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nextflow-io/metaGT/contents/main.nf
```

Please suggest how to fix this error? Thank you.

**Comment by andrewprzh** [comment]
Dear @JSSaini 

You need to clone the repository first and then run the command from the same folder as indicated in the manual.
Hope that helps!

Best
Andrey

**Comment by JSSaini** [comment]
I need to install dependencies. Rest is good. Thanks.

**Comment by andrewprzh** [comment]
@JSSaini 

Normally Nexflow intalls everything by itself (and it was previously). We will update the config to fix that soon.

Best
Andrey

**Comment by andrewprzh** [comment]
Should be fixed now.
