### ISSUE TITLE
Aligning Metagenome-assembled genomes to metatranscriptomics libraries command line?

### ISSUE THREAD

**Issue by JSSaini** [ablab/metaGT#5]
Hi, 
I would like to align the list of metagenome-assembled genomes to merged-metatranscriptomics libraries. Please suggest a reasonable command to run MetaGT? I tried the following, but it complains about genome input, maybe because of absolute paths.

`nextflow run /media/bioinfoteam/SCRATCH_1TB/jssaini_scratch/github/metaGT/metaGT m -genome '*/media/bioinfoteam/SCRATCH_1TB/jssaini_scratch/Aline_MAGs/Aline_JS_combo/All_MAGs_work_13_Feb/stag_bins/drep_results_90_10/dereplicated_genomes/bakta_derep_mags_results/MAGs_2.5k/*.fa' --transcriptome '*.fastq'`

Unknown option: -genome -- Check the available commands and options and syntax with 'help'

And how to open help documentation?  Thank you for your kind assistance.

**Comment by andrewprzh** [comment]
Dear @JSSaini 

Sorry for the late response.

To get available options you can run `nextflow run metaGT -profile conda --help`. I'll add information to the README soon.

To provide assembled metagenomes the option is correct except you forgot a second dash: `--genome`
To provide RNA reads I suggest to use `--rna_reads` option.

If you encounter more problems do not hesitate to contact and send me the error message.

All the best
Andrey
